.Dd $Mdocdate:  October 25 2023 $
.Dt NCOD 1
.Os
.Sh NAME
.Nm ncod
.Nd Minimalistic CLI password manager

.Sh SYNOPSIS
.Nm ncad
.Fl i | g | s | l | u | d
.Op Ar secret_id
.Op Fl f Ar file

.Sh DESCRIPTION
The
.Nm
is a utility for storing usernames and password in encrypted file.
It us meant to be as simple as possible while providing
the bare minimum of functionality.

Usage:
.Bl -tag -width Ds
.It Fl i
Initialize secure storage
.It Fl g Ar secret_id
Get secret from storage
.It Fl s Ar secret_id
Put secret to storage (you will be prompted for username and password)
.It Fl u Ar secret_id
Update secret in storage (you will be prompted for username and password)
.It Fl d Ar secret_id
Delete secret from storage (you will be prompted for username and password)
.It Fl l
List all secrets in storage (only IDs and usernames)
.El

You can also specify file to use for storage using
.Fl f Ar file

.Sh EXIT STATUS
Exits 0 on success and -1 if an error occurs.

.Sh FILES
.Bl -tag -width indent -compact
.It Pa ~/.ncod.db
Default location of password storage
